### ISSUE TITLE
Can't Browse Code To Root

### ISSUE THREAD

**Issue by patgmiller** [kba7/trugithub#10]
While browsing the code as soon as I enter a folder in the root, I can not get back to the root of the repo. I can get back to the first level folder if I enter another sub folder, but not the root. 

I tried tapping on the name of the first level folder to exit it, but that failed to do anything. 

Perhaps it would be helpful to include the root folder as a breadcrumb like the other folder. 

I am using the app on a Samsung S4.

**Comment by patgmiller** [comment]
**Update:** the back button on my phone works to get to root folder of repo.

**Comment by jonan** [comment]
This is working fine in the original app https://github.com/jonan/ForkHub

**Comment by patgmiller** [comment]
Yes it is working great, thanks I'll switch to the original app. This is a great app, thanks for maintaining it.
