### ISSUE TITLE
Separate pull requests from issues

### ISSUE THREAD

**Issue by madpipeline** [kba7/trugithub#13]
Having issues and pull requests mixed together makes it harder to identify which is which, and thus on which to act first.

**Comment by jonan** [comment]
If you want this to be implemented, you should report it to the original app https://github.com/jonan/ForkHub. This app is just a copy.

This issue is probably the same as https://github.com/jonan/ForkHub/issues/189

**Comment by madpipeline** [comment]
Then I'll close this.
