### ISSUE TITLE
Change locale of app manually

### ISSUE THREAD

**Issue by gioragutt** [kba7/trugithub#16]
Hi, my phone's language is hebrew, and the app automatically localizes to hebrew. I prefer English in this case, since some of the translations are lackluster, and I generally prefer to use English when programming. An option to manually change the language of the app would be great!

**Comment by jonan** [comment]
If you want this to be fixed, you should report it to the original app https://github.com/jonan/ForkHub. This app is just a copy.

This issue is probably the same as https://github.com/jonan/ForkHub/issues/82
