### ISSUE TITLE
How do I change language? 

### ISSUE THREAD

**Issue by Tranberry** [kba7/trugithub#20]
It's very confusing when words that usually are English even in my native language gets translated.

**Comment by jonan** [comment]
If you want this to be fixed, you should report it to the original app https://github.com/jonan/ForkHub. This app is just a copy.

This issue is probably the same as https://github.com/jonan/ForkHub/issues/82

**Comment by Tranberry** [comment]
Thanks, strange that the app pointed here.

Maybe report it as a bug?

**Comment by jonan** [comment]
You probably downloaded the wrong app, the original one is https://play.google.com/store/apps/details?id=jp.forkhub

**Comment by Tranberry** [comment]
Interesting that the app I downloaded was the first hit on the play store gave me while just searching for 'GitHub'.

**Comment by Raisoumia94** [comment]
I 'm not agree with u

**Comment by Tranberry** [comment]
I don't understand what you mean.
