### ISSUE TITLE
Can't load issues

### ISSUE THREAD

**Issue by pires** [kba7/trugithub#30]
Here's a screenshot  https://drive.google.com/file/d/0B2hySBwNSLlVVWkwbkg5bU4tSUE/view?usp=drivesdk

**Comment by jonan** [comment]
If you want this to be fixed, you should report it to the original app https://github.com/jonan/ForkHub. This app is just a copy.

I can't reproduce the bug in ForkHub, but if you can, please report the issue and I'll take a look at it.
