### ISSUE TITLE
Issue Dashboard/Created doesn't show my created issues

### ISSUE THREAD

**Issue by ymg2006** [kba7/trugithub#33]
I dont know but other apps are showing,  i loved your work,  except this part which is not working.
This section ia empty,  but i created Issues on repository.

**Comment by jonan** [comment]
If you want this to be fixed, you should report it to the original app https://github.com/jonan/ForkHub. This app is just a copy.

This issue is probably the same as https://github.com/jonan/ForkHub/issues/106
