### ISSUE TITLE
Hitting back arrow button takes you to wrong place

### ISSUE THREAD

**Issue by skaefer143** [kba7/trugithub#38]
After opening a repository, hitting the back button on the Android phone takes you back yet your repository listings, but then when you hit the back arrow button in the top left corner, it brings you to the person's profile who made the repo. Also seems like it launches into that. Hitting back again brings you back to the repository listing. 

Not sure if intentional or not, but kinda confusing for a user.

**Comment by jonan** [comment]
If you want this to be implemented, you should report it to the original app https://github.com/jonan/ForkHub. This app is just a copy.
