### ISSUE TITLE
Random gist

### ISSUE THREAD

**Issue by jb3** [kba7/trugithub#39]
I click random gist but keep getting an error I will try get screenshot

**Comment by jb3** [comment]
The error reads:

```

Parcelable encountered IOException

writing serializable object (name org

eclipse egit github core.Gist)

```

**Comment by jonan** [comment]
If you want this to be fixed, you should report it to the original app https://github.com/jonan/ForkHub. This app is just a copy.

I can't reproduce the bug in ForkHub, but if you can, please report the issue and I'll take a look at it.

**Comment by jb3** [comment]
Ahh Ok, I didn't see ForkHub while getting this app so I'll take a look at ForkHub now, Thanks
